[package]
name = "user_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "hello_world"
path = "src/hello_world.rs"

[[bin]]
name = "loop10"
path = "src/loop10.rs"
